### ISSUE TITLE
Hi! How is it going?

### ISSUE THREAD

**Issue by Ucsus** [dmonty2/homeassistant_wled_mqtt#1]
I connected your config, on/off and brightness work, effects and presets in the light settings work, but I can’t select an effect/color/preset in automations - only on/off and brightness.
**UPD:** It was possible to launch the effect by writing the full name `[FX=001] Blink`
But how to change the color? In the light properties the color changes to the one set in automation, but on the LED it doesn’t

**Comment by dmonty2** [comment]
Under the effect drop-down in homeassistant there are 3 sections: Presets, Effects, & Pallets.  The effect has to be set to "solid" for solid color changes.  For effect pallets you will find them at the bottom of the Effect list.

That being said. I'm still getting the odd white flash when using mqtt.

**Comment by dmonty2** [comment]
![fx000_solid](https://github.com/dmonty2/homeassistant_wled_mqtt/assets/1381071/0934aaed-5645-4ca0-8519-d885208fb864)

**Comment by Ucsus** [comment]
Thanks, I did it like this https://pastebin.com/hHJLAxce
Everything seems to be working.

**Comment by dmonty2** [comment]
Some fixes to the code.
![some_fixes](https://github.com/dmonty2/homeassistant_wled_mqtt/assets/1381071/20fb3533-4085-4bc1-9365-85f3ff3fc64b)
